#ifndef __X10_LANG_LATCH_H
#define __X10_LANG_LATCH_H

#include <x10rt.h>


#define X10_LANG_MONITOR_H_NODEPS
#include <x10/lang/Monitor.h>
#undef X10_LANG_MONITOR_H_NODEPS
#define X10_LANG_FUN_0_0_H_NODEPS
#include <x10/lang/Fun_0_0.h>
#undef X10_LANG_FUN_0_0_H_NODEPS
#define X10_LANG_BOOLEAN_STRUCT_H_NODEPS
#include <x10/lang/Boolean.struct_h>
#undef X10_LANG_BOOLEAN_STRUCT_H_NODEPS
namespace x10 { namespace lang { 
class Boolean;
} } 
#include <x10/lang/Boolean.struct_h>
namespace x10 { namespace lang { 
class Any;
} } 
namespace x10 { namespace lang { 
class UnsupportedOperationException;
} } 
namespace x10 { namespace lang { 
class String;
} } 
namespace x10 { namespace lang { 
class Runtime;
} } 
namespace x10 { namespace compiler { 
class Pinned;
} } 
namespace x10 { namespace lang { 

class Latch : public x10::lang::Monitor   {
    public:
    RTT_H_DECLS_CLASS
    
    static x10aux::itable_entry _itables[4];
    
    virtual x10aux::itable_entry* _getITables() { return _itables; }
    
    static x10::io::CustomSerialization::itable<x10::lang::Latch > _itable_0;
    
    static x10::lang::Any::itable<x10::lang::Latch > _itable_1;
    
    static x10::lang::Fun_0_0<x10_boolean>::itable<x10::lang::Latch > _itable_2;
    
    void _instance_init();
    
    void _constructor();
    
    static x10aux::ref<x10::lang::Latch> _make();
    
    void _constructor(x10aux::ref<x10::lang::Any> id__130);
    
    static x10aux::ref<x10::lang::Latch> _make(x10aux::ref<x10::lang::Any> id__130);
    
    x10_boolean FMGL(state);
    
    virtual void release();
    virtual void await();
    virtual x10_boolean __apply();
    virtual x10aux::ref<x10::lang::Latch> x10__lang__Latch____x10__lang__Latch__this(
      );
    void __fieldInitializers1939();
    
    // Serialization
    public: static const x10aux::serialization_id_t _serialization_id;
    
    public: virtual x10aux::serialization_id_t _get_serialization_id() {
         return _serialization_id;
    }
    
    // autogenerated custom deserialization
    void _constructor(x10aux::ref<x10::io::SerialData> sd) {
        x10::lang::Monitor::_constructor(sd);
    }
    
    public: virtual void _serialize_body(x10aux::serialization_buffer& buf);
    
    public: template<class __T> static x10aux::ref<__T> _deserializer(x10aux::deserialization_buffer& buf);
    
    public: void _deserialize_body(x10aux::deserialization_buffer& buf);
    
};

} } 
#endif // X10_LANG_LATCH_H

namespace x10 { namespace lang { 
class Latch;
} } 

#ifndef X10_LANG_LATCH_H_NODEPS
#define X10_LANG_LATCH_H_NODEPS
#include <x10/lang/Monitor.h>
#include <x10/lang/Fun_0_0.h>
#include <x10/lang/Boolean.h>
#include <x10/lang/Any.h>
#include <x10/lang/UnsupportedOperationException.h>
#include <x10/lang/String.h>
#include <x10/lang/Runtime.h>
#include <x10/compiler/Pinned.h>
#ifndef X10_LANG_LATCH_H_GENERICS
#define X10_LANG_LATCH_H_GENERICS
template<class __T> x10aux::ref<__T> x10::lang::Latch::_deserializer(x10aux::deserialization_buffer& buf) {
    x10aux::ref<x10::lang::Latch> this_ = new (memset(x10aux::alloc<x10::lang::Latch>(), 0, sizeof(x10::lang::Latch))) x10::lang::Latch();
    buf.record_reference(this_);
    this_->_deserialize_body(buf);
    return this_;
}

#endif // X10_LANG_LATCH_H_GENERICS
#endif // __X10_LANG_LATCH_H_NODEPS
